<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../YoAIWorkflow.Abstractions/YoAIWorkflow.Abstractions.csproj" />
    <ProjectReference Include="../YoAIWorkflow.Core/YoAIWorkflow.Core.csproj" />
  </ItemGroup>
</Project>
